package edu.upc.prop.presentacio;

import javax.swing.JOptionPane;

public class PanelSequenciaDades extends javax.swing.JPanel {

    private ControladorPresentacioSequencies controladorSequencies;

    /**
     * Creates new form PanelSimptomaDades
     */
    public PanelSequenciaDades(ControladorPresentacioSequencies controladorSequencies) {
        this.controladorSequencies = controladorSequencies;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButtonAcceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSequencia = new javax.swing.JTextArea();
        jLabelFormat = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setText("Seqüència:");

        jButtonAcceptar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonAcceptar.setText("Acceptar");
        jButtonAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextAreaSequencia.setColumns(20);
        jTextAreaSequencia.setLineWrap(true);
        jTextAreaSequencia.setRows(5);
        jTextAreaSequencia.setWrapStyleWord(true);
        jTextAreaSequencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaSequenciaFocusGained(evt);
            }
        });
        jTextAreaSequencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaSequenciaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaSequenciaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaSequencia);

        jLabelFormat.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabelFormat.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 533, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAcceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFormat))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFormat)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptarActionPerformed
        String sequencia = jTextAreaSequencia.getText();

        if (sequencia.equals("")) {
            jLabelFormat.setText("Cal introduir una seqüència");
            return;
        }

        String msg;
        String title;
        int opcio = JOptionPane.ERROR_MESSAGE;

        boolean insertat;
        title = "Nova sequencia";
        try {
            insertat = controladorSequencies.addSequencia(sequencia);

            if (insertat) {
                try {
                    long id = controladorSequencies.getId(sequencia);
                    if (id != -1) {
                        controladorSequencies.redibuixarVista(id);
                        controladorSequencies.seleccionaSequencia(id);
                    }
                } catch (StackOverflowError sof) {
                    JOptionPane.showMessageDialog(this, "Hi ha hagut un problema", "", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                msg = "No s'ha pogut insertar. Pot ser que ja existeixi";
                JOptionPane.showMessageDialog(this, msg, title, opcio);
            }
        } catch (StackOverflowError sor) {
            msg = "La seqüència és massa llarga";
            Runtime.getRuntime().gc();
            JOptionPane.showMessageDialog(this, msg, title, opcio);
        }
    }//GEN-LAST:event_jButtonAcceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        controladorSequencies.cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextAreaSequenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaSequenciaFocusGained
        jLabelFormat.setText("");
    }//GEN-LAST:event_jTextAreaSequenciaFocusGained

    private void jTextAreaSequenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaSequenciaKeyTyped
        controladorSequencies.setModificant();
    }//GEN-LAST:event_jTextAreaSequenciaKeyTyped

    private void jTextAreaSequenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaSequenciaKeyReleased
        String text = jTextAreaSequencia.getText();

        jTextAreaSequencia.setText(text.toUpperCase());
    }//GEN-LAST:event_jTextAreaSequenciaKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAcceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaSequencia;
    // End of variables declaration//GEN-END:variables
}
