package edu.upc.prop.presentacio;

import java.awt.Color;
import java.awt.Insets;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class PanelPatronsConeguts extends javax.swing.JPanel {

    private ControladorPresentacioEstudis controladorEstudis;
    private ControladorPresentacioSimptomes controladorSimptomes;
    private ControladorPresentacioMalalties controladorMalalties;
    private ControladorPresentacioPacients controladorPacients;
    private ControladorPresentacioSequencies controladorSequencies;
    private DialogAfegirPacient dialogAfegirPacient;
    private DialogAfegirMalaltia dialogAfegirMalaltia;
    private DialogAfegirSimptoma dialogAfegirSimptoma;
    private DialogAfegirSequencia dialogAfegirSequencia;
    private DefaultListModel modelPacients;
    private DefaultListModel modelMalalties;
    private DefaultListModel modelSimptomes;
    private DefaultListModel modelPatrons;
    private static final Color disabledColor = new Color(239, 242, 249);

    /**
     * Creates new form PanelPatronsConeguts
     */
//    public PanelPatronsConeguts(ControladorPresentacioEstudis controladorEstudis) {
    public PanelPatronsConeguts(ControladorPresentacioEstudis controladorEstudis,
            ControladorPresentacioPacients controladorPacients, ControladorPresentacioMalalties controladorMalalties,
            ControladorPresentacioSimptomes controladorSimptomes, ControladorPresentacioSequencies controladorSequencies) {
        this.controladorEstudis = controladorEstudis;

        this.controladorPacients = controladorPacients;
        this.controladorMalalties = controladorMalalties;
        this.controladorSimptomes = controladorSimptomes;
        this.controladorSequencies = controladorSequencies;

        modelPacients = new DefaultListModel();
        modelMalalties = new DefaultListModel();
        modelSimptomes = new DefaultListModel();
        modelPatrons = new DefaultListModel();

        initComponents();
        controladorEstudis.setPatronsConeguts(this);

        jListPacients.setModel(modelPacients);
        jListMalalties.setModel(modelMalalties);
        jListSimptomes.setModel(modelSimptomes);
        jListPatrons.setModel(modelPatrons);

        URL loca = ClassLoader.getSystemResource("edu/upc/prop/icons/interrogante.png");
        if (loca != null) {
            ImageIcon icono = new ImageIcon(Toolkit.getDefaultToolkit().getImage(loca));
            jToggleInstruccions.setIcon(icono);
            jToggleInstruccions.setMargin(new Insets(2, 2, 2, 2));
        } else {
            jToggleInstruccions.setText("?");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexe = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEdatInici = new javax.swing.JTextField();
        jTextFieldEdatFi = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDNIInici = new javax.swing.JTextField();
        jTextFieldDNIFi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelFormat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonMasculi = new javax.swing.JRadioButton();
        jRadioButtonFemeni = new javax.swing.JRadioButton();
        jRadioButtonTot = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPacients = new javax.swing.JList();
        jButtonMesPacients = new javax.swing.JButton();
        jButtonMenysPacients = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMalalties = new javax.swing.JList();
        jButtonMenysMalalties = new javax.swing.JButton();
        jButtonMesMalalties = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSimptomes = new javax.swing.JList();
        jButtonMenysSimptomes = new javax.swing.JButton();
        jButtonMesSimptomes = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPatrons = new javax.swing.JList();
        jButtonMenysPatrons = new javax.swing.JButton();
        jButtonMesPatrons = new javax.swing.JButton();
        jLabelInstruccions = new javax.swing.JLabel();
        jToggleInstruccions = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQ = new javax.swing.JTextField();
        jTextFieldError = new javax.swing.JTextField();
        jTextFieldLongMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLongMax = new javax.swing.JTextField();
        jCheckBoxinsertions = new javax.swing.JCheckBox();
        jCheckBoxParalelo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel2.setText("Inici:");

        jLabel3.setText("Fi:");

        jTextFieldEdatInici.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdatIniciKeyTyped(evt);
            }
        });

        jTextFieldEdatFi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdatFiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEdatInici, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jTextFieldEdatFi))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEdatInici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldEdatFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel4.setText("Inici:");

        jTextFieldDNIInici.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDNIIniciFocusGained(evt);
            }
        });
        jTextFieldDNIInici.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIIniciKeyTyped(evt);
            }
        });

        jTextFieldDNIFi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDNIFiFocusGained(evt);
            }
        });
        jTextFieldDNIFi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIFiKeyTyped(evt);
            }
        });

        jLabel5.setText("Fi:");

        jLabelFormat.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDNIInici, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFormat))
                    .addComponent(jTextFieldDNIFi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNIInici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldDNIFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        buttonGroupSexe.add(jRadioButtonMasculi);
        jRadioButtonMasculi.setText("Masculi");

        buttonGroupSexe.add(jRadioButtonFemeni);
        jRadioButtonFemeni.setText("Femeni");

        buttonGroupSexe.add(jRadioButtonTot);
        jRadioButtonTot.setSelected(true);
        jRadioButtonTot.setText("Tot");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMasculi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemeni))
                    .addComponent(jRadioButtonTot))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFemeni)
                    .addComponent(jRadioButtonMasculi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTot))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacients", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jScrollPane1.setViewportView(jListPacients);

        jButtonMesPacients.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMesPacients.setText("+");
        jButtonMesPacients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesPacientsActionPerformed(evt);
            }
        });

        jButtonMenysPacients.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMenysPacients.setText("-");
        jButtonMenysPacients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenysPacientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMenysPacients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMesPacients))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMesPacients)
                    .addComponent(jButtonMenysPacients)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Malalties", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jScrollPane2.setViewportView(jListMalalties);

        jButtonMenysMalalties.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMenysMalalties.setText("-");
        jButtonMenysMalalties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenysMalaltiesActionPerformed(evt);
            }
        });

        jButtonMesMalalties.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMesMalalties.setText("+");
        jButtonMesMalalties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesMalaltiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMenysMalalties)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMesMalalties))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMesMalalties)
                    .addComponent(jButtonMenysMalalties)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simptomes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jScrollPane3.setViewportView(jListSimptomes);

        jButtonMenysSimptomes.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMenysSimptomes.setText("-");
        jButtonMenysSimptomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenysSimptomesActionPerformed(evt);
            }
        });

        jButtonMesSimptomes.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMesSimptomes.setText("+");
        jButtonMesSimptomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesSimptomesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMenysSimptomes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMesSimptomes))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMesSimptomes)
                    .addComponent(jButtonMenysSimptomes)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patrons", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jScrollPane4.setViewportView(jListPatrons);

        jButtonMenysPatrons.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMenysPatrons.setText("-");
        jButtonMenysPatrons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenysPatronsActionPerformed(evt);
            }
        });

        jButtonMesPatrons.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jButtonMesPatrons.setText("+");
        jButtonMesPatrons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesPatronsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMenysPatrons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMesPatrons))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMesPatrons)
                    .addComponent(jButtonMenysPatrons)))
        );

        jLabelInstruccions.setForeground(new java.awt.Color(100, 100, 100));
        jLabelInstruccions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInstruccions.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jToggleInstruccions.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleInstruccionsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleInstruccions, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInstruccions, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jToggleInstruccions)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInstruccions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3});

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Execucio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel1.setText("Q:");

        jLabel6.setText("Error (%):");

        jTextFieldQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQKeyTyped(evt);
            }
        });

        jTextFieldError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldErrorKeyTyped(evt);
            }
        });

        jTextFieldLongMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLongMinKeyTyped(evt);
            }
        });

        jLabel7.setText("Longitud Mínima:");

        jLabel8.setText("Longitud Màxima:");

        jTextFieldLongMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLongMaxKeyTyped(evt);
            }
        });

        jCheckBoxinsertions.setText("Ins & Del");

        jCheckBoxParalelo.setText("Paral·lel");

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLongMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxParalelo)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxinsertions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldError, jTextFieldLongMax, jTextFieldLongMin, jTextFieldQ});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldLongMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxParalelo)
                    .addComponent(jCheckBoxinsertions)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCheckBoxParalelo, jCheckBoxinsertions, jLabel1, jLabel6, jLabel7, jLabel8, jTextFieldError, jTextFieldLongMax, jTextFieldLongMin, jTextFieldQ});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<String> llista = new ArrayList<String>();
//        for (int i = 0; i < jListPacients.getModel().getSize(); i++) {
//            llista.add((String) jListPacients.getModel().getElementAt(i));
//        }
        for (int i = 0; i < modelPacients.size(); i++) {
            String pacient = (String) modelPacients.get(i);
            llista.add(pacient.substring(0, pacient.indexOf(":")).trim());
        }
        controladorEstudis.setDnis(llista);
        llista.clear();

//        for (int i = 0; i < jListMalalties.getModel().getSize(); i++) {
//            llista.add((String) jListMalalties.getModel().getElementAt(i));
//        }
        for (int i = 0; i < modelMalalties.size(); i++) {
            llista.add((String) modelMalalties.get(i));
        }
        controladorEstudis.setMalalties(llista);
        llista.clear();

//        for (int i = 0; i < jListSimptomes.getModel().getSize(); i++) {
//            llista.add((String) jListSimptomes.getModel().getElementAt(i));
//        }
        for (int i = 0; i < modelSimptomes.size(); i++) {
            llista.add((String) modelSimptomes.get(i));
        }
        controladorEstudis.setSimptomes(llista);
        llista.clear();

//        for (int i = 0; i < jListPatrons.getModel().getSize(); i++) {
//            llista.add((String) jListPatrons.getModel().getElementAt(i));
//        }
        for (int i = 0; i < modelPatrons.size(); i++) {
            String patro = (String) modelPatrons.get(i);
            llista.add(patro.substring(patro.indexOf(":") + 1).trim());
        }
        controladorEstudis.setPatronsConeguts(llista);

        if (!jTextFieldDNIFi.getText().isEmpty()) {
            if (jTextFieldDNIFi.getText().length() != 8) {
                jLabelFormat.setText("El Dni ha de tenir 8 dígits");
                return;
            }
            controladorEstudis.setDniFinal(jTextFieldDNIFi.getText());
        } else {
            controladorEstudis.setDniFinal(null);
        }

        if (!jTextFieldDNIInici.getText().isEmpty()) {
            if (jTextFieldDNIInici.getText().length() != 8) {
                jLabelFormat.setText("El Dni ha de tenir 8 dígits");
                return;
            }
            controladorEstudis.setDniInici(jTextFieldDNIInici.getText());
        } else {
            controladorEstudis.setDniInici(null);
        }

        if (!jTextFieldEdatFi.getText().isEmpty()) {
            controladorEstudis.setEdatFi(Integer.parseInt(jTextFieldEdatFi.getText()));
        } else {
            controladorEstudis.setEdatFi(-1);
        }

        if (!jTextFieldEdatInici.getText().isEmpty()) {
            controladorEstudis.setEdatInici(Integer.parseInt(jTextFieldEdatInici.getText()));
        } else {
            controladorEstudis.setEdatInici(-1);
        }

        if (jRadioButtonFemeni.isSelected()) {
            controladorEstudis.setSexe('F');
        } else if (jRadioButtonMasculi.isSelected()) {
            controladorEstudis.setSexe('M');
        } else {
            controladorEstudis.setSexe('X');
        }

        if (!jTextFieldQ.getText().isEmpty()) {
            controladorEstudis.setQ(Integer.parseInt(jTextFieldQ.getText()));
        } else {
            controladorEstudis.setQ(-1);
        }

        if (!jTextFieldError.getText().isEmpty()) {
            controladorEstudis.setMargeError(Double.parseDouble(jTextFieldError.getText()) / 100.0);
        } else {
            controladorEstudis.setMargeError(0.01);
        }

        if (!jTextFieldLongMax.getText().isEmpty()) {
            controladorEstudis.setLongMax(Integer.parseInt(jTextFieldLongMax.getText()));
        } else {
            controladorEstudis.setLongMax( Integer.MAX_VALUE / 1000);
        }

        if (!jTextFieldLongMin.getText().isEmpty()) {
            controladorEstudis.setLongMin(Integer.parseInt(jTextFieldLongMin.getText()));
        } else {
            controladorEstudis.setLongMin(0);
        }

        ponerGif();
        disableTot();
        controladorEstudis.buscarPatronsExistents(jCheckBoxParalelo.isSelected(), jCheckBoxinsertions.isSelected());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldDNIIniciFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDNIIniciFocusGained
        jLabelFormat.setText("");
    }//GEN-LAST:event_jTextFieldDNIIniciFocusGained

    private void jTextFieldDNIFiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDNIFiFocusGained
        jLabelFormat.setText("");
    }//GEN-LAST:event_jTextFieldDNIFiFocusGained

    private void jButtonMesPacientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesPacientsActionPerformed
        dialogAfegirPacient = new DialogAfegirPacient(controladorPacients);
        dialogAfegirPacient.setVisible(true);
        if (dialogAfegirPacient.isAcceptat()) {
            for (String pacient : dialogAfegirPacient.getPacientsSeleccionats()) {
                modelPacients.addElement(pacient);
            }
        }
    }//GEN-LAST:event_jButtonMesPacientsActionPerformed

    private void jButtonMenysPacientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenysPacientsActionPerformed
        int index = jListPacients.getSelectedIndex();
        if (index != -1) {
            modelPacients.remove(index);
        }
    }//GEN-LAST:event_jButtonMenysPacientsActionPerformed

    private void jButtonMenysMalaltiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenysMalaltiesActionPerformed
        int index = jListMalalties.getSelectedIndex();
        if (index != -1) {
            modelMalalties.remove(index);
        }
    }//GEN-LAST:event_jButtonMenysMalaltiesActionPerformed

    private void jButtonMesMalaltiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesMalaltiesActionPerformed
        dialogAfegirMalaltia = new DialogAfegirMalaltia(controladorMalalties);
        dialogAfegirMalaltia.setVisible(true);
        if (dialogAfegirMalaltia.isAcceptat()) {
            for (String malaltia : dialogAfegirMalaltia.getMalaltiesSeleccionats()) {
                modelMalalties.addElement(malaltia);
            }
        }

    }//GEN-LAST:event_jButtonMesMalaltiesActionPerformed

    private void jButtonMenysSimptomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenysSimptomesActionPerformed
        int index = jListSimptomes.getSelectedIndex();
        if (index != -1) {
            modelSimptomes.remove(index);
        }
    }//GEN-LAST:event_jButtonMenysSimptomesActionPerformed

    private void jButtonMesSimptomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesSimptomesActionPerformed
        dialogAfegirSimptoma = new DialogAfegirSimptoma(controladorSimptomes);
        dialogAfegirSimptoma.setVisible(true);
        if (dialogAfegirSimptoma.isAcceptat()) {
            for (String simptoma : dialogAfegirSimptoma.getSimtomesSeleccionats()) {
                modelSimptomes.addElement(simptoma);
            }
        }
    }//GEN-LAST:event_jButtonMesSimptomesActionPerformed

    private void jButtonMenysPatronsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenysPatronsActionPerformed
        int index = jListPatrons.getSelectedIndex();
        if (index != -1) {
            modelPatrons.remove(index);
        }
    }//GEN-LAST:event_jButtonMenysPatronsActionPerformed

    private void jButtonMesPatronsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesPatronsActionPerformed
        dialogAfegirSequencia = new DialogAfegirSequencia(controladorSequencies);
        dialogAfegirSequencia.setVisible(true);
        if (dialogAfegirSequencia.isAcceptat()) {
            for (String patro : dialogAfegirSequencia.getSequenciesSeleccionats()) {
                modelPatrons.addElement(patro);
            }
        }
    }//GEN-LAST:event_jButtonMesPatronsActionPerformed

    private void jToggleInstruccionsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleInstruccionsStateChanged
        if (jToggleInstruccions.isSelected()) {
            jLabelInstruccions.setText("<html><p align=\"right\">Tots els camps són opcionals.</p><br>"
                    + "<p align=\"right\">Els camps en blanc prendran els valors per defecte.</p><br>"
                    + "<p align=\"right\">Els camps d'Edat, DNI, Q, Longitud Mínima i <br>"
                    + "Longitud Màxima requereixen nombres enters.</p><br>"
                    + "<p align=\"right\">El camp Error requereix un nombre real.</p></html>");
        } else {
            jLabelInstruccions.setText("");
        }
    }//GEN-LAST:event_jToggleInstruccionsStateChanged

    private void jTextFieldEdatIniciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdatIniciKeyTyped
        intInputVerifier(jTextFieldEdatInici.getText(), evt);
    }//GEN-LAST:event_jTextFieldEdatIniciKeyTyped

    private void jTextFieldEdatFiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdatFiKeyTyped
        intInputVerifier(jTextFieldEdatFi.getText(), evt);
    }//GEN-LAST:event_jTextFieldEdatFiKeyTyped

    private void jTextFieldDNIIniciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIIniciKeyTyped
        intInputVerifier(jTextFieldDNIInici.getText(), evt);
    }//GEN-LAST:event_jTextFieldDNIIniciKeyTyped

    private void jTextFieldDNIFiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIFiKeyTyped
        intInputVerifier(jTextFieldDNIFi.getText(), evt);
    }//GEN-LAST:event_jTextFieldDNIFiKeyTyped

    private void jTextFieldQKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQKeyTyped
        intInputVerifier(jTextFieldQ.getText(), evt);
    }//GEN-LAST:event_jTextFieldQKeyTyped

    private void jTextFieldLongMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLongMinKeyTyped
        intInputVerifier(jTextFieldLongMin.getText(), evt);
    }//GEN-LAST:event_jTextFieldLongMinKeyTyped

    private void jTextFieldLongMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLongMaxKeyTyped
        intInputVerifier(jTextFieldLongMax.getText(), evt);
    }//GEN-LAST:event_jTextFieldLongMaxKeyTyped

    private void jTextFieldErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldErrorKeyTyped
        doubleInputVerifier(jTextFieldError.getText(), evt);
    }//GEN-LAST:event_jTextFieldErrorKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMenysMalalties;
    private javax.swing.JButton jButtonMenysPacients;
    private javax.swing.JButton jButtonMenysPatrons;
    private javax.swing.JButton jButtonMenysSimptomes;
    private javax.swing.JButton jButtonMesMalalties;
    private javax.swing.JButton jButtonMesPacients;
    private javax.swing.JButton jButtonMesPatrons;
    private javax.swing.JButton jButtonMesSimptomes;
    private javax.swing.JCheckBox jCheckBoxParalelo;
    private javax.swing.JCheckBox jCheckBoxinsertions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelInstruccions;
    private javax.swing.JList jListMalalties;
    private javax.swing.JList jListPacients;
    private javax.swing.JList jListPatrons;
    private javax.swing.JList jListSimptomes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonFemeni;
    private javax.swing.JRadioButton jRadioButtonMasculi;
    private javax.swing.JRadioButton jRadioButtonTot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldDNIFi;
    private javax.swing.JTextField jTextFieldDNIInici;
    private javax.swing.JTextField jTextFieldEdatFi;
    private javax.swing.JTextField jTextFieldEdatInici;
    private javax.swing.JTextField jTextFieldError;
    private javax.swing.JTextField jTextFieldLongMax;
    private javax.swing.JTextField jTextFieldLongMin;
    private javax.swing.JTextField jTextFieldQ;
    private javax.swing.JToggleButton jToggleInstruccions;
    // End of variables declaration//GEN-END:variables

    private void disableTot() {
        jButton1.setEnabled(false);
        jTextFieldDNIInici.setEnabled(false);
        jTextFieldDNIFi.setEnabled(false);
        jTextFieldEdatInici.setEnabled(false);
        jTextFieldEdatFi.setEnabled(false);
        jTextFieldError.setEnabled(false);
        jTextFieldLongMax.setEnabled(false);
        jTextFieldLongMin.setEnabled(false);
        jTextFieldQ.setEnabled(false);
        jCheckBoxParalelo.setEnabled(false);
        jCheckBoxinsertions.setEnabled(false);
        jRadioButtonFemeni.setEnabled(false);
        jRadioButtonMasculi.setEnabled(false);
        jRadioButtonTot.setEnabled(false);
        jListMalalties.setEnabled(false);
        jListPacients.setEnabled(false);
        jListPatrons.setEnabled(false);
        jListSimptomes.setEnabled(false);

        jTextFieldDNIFi.setBackground(disabledColor);
        jTextFieldDNIInici.setBackground(disabledColor);
        jTextFieldEdatFi.setBackground(disabledColor);
        jTextFieldEdatInici.setBackground(disabledColor);
        jTextFieldError.setBackground(disabledColor);
        jTextFieldLongMax.setBackground(disabledColor);
        jTextFieldLongMin.setBackground(disabledColor);
        jTextFieldQ.setBackground(disabledColor);
        jListMalalties.setBackground(disabledColor);
        jListPacients.setBackground(disabledColor);
        jListPatrons.setBackground(disabledColor);
        jListSimptomes.setBackground(disabledColor);
    }

    private void ponerGif() {
        controladorEstudis.posarGif();
    }

    public void enableTot() {
        jButton1.setEnabled(true);
        jTextFieldDNIInici.setEnabled(true);
        jTextFieldDNIFi.setEnabled(true);
        jTextFieldEdatInici.setEnabled(true);
        jTextFieldEdatFi.setEnabled(true);
        jTextFieldError.setEnabled(true);
        jTextFieldLongMax.setEnabled(true);
        jTextFieldLongMin.setEnabled(true);
        jTextFieldQ.setEnabled(true);
        jCheckBoxParalelo.setEnabled(true);
        jCheckBoxinsertions.setEnabled(true);
        jRadioButtonFemeni.setEnabled(true);
        jRadioButtonMasculi.setEnabled(true);
        jRadioButtonTot.setEnabled(true);
        jListMalalties.setEnabled(true);
        jListPacients.setEnabled(true);
        jListPatrons.setEnabled(true);
        jListSimptomes.setEnabled(true);

        jTextFieldDNIFi.setBackground(Color.white);
        jTextFieldDNIInici.setBackground(Color.white);
        jTextFieldEdatFi.setBackground(Color.white);
        jTextFieldEdatInici.setBackground(Color.white);
        jTextFieldError.setBackground(Color.white);
        jTextFieldLongMax.setBackground(Color.white);
        jTextFieldLongMin.setBackground(Color.white);
        jTextFieldQ.setBackground(Color.white);
        jListMalalties.setBackground(Color.white);
        jListPacients.setBackground(Color.white);
        jListPatrons.setBackground(Color.white);
        jListSimptomes.setBackground(Color.white);

    }

    private void intInputVerifier(String anterior, java.awt.event.KeyEvent evt) {
        char key = evt.getKeyChar();
        try {
            Integer.parseInt(anterior + key);
        } catch (Exception e) {
            evt.setKeyChar('\0');
        }
    }

    private void doubleInputVerifier(String anterior, java.awt.event.KeyEvent evt) {
        char key = evt.getKeyChar();
        try {
            Double.parseDouble(anterior + key);
        } catch (Exception e) {
            evt.setKeyChar('\0');
        }
    }
}
