package edu.upc.prop.presentacio;

public class PanelSequenciaConsulta extends javax.swing.JPanel {

    private ControladorPresentacioSequencies controladorSequencies;

    /**
     * Creates new form PanelSimptomaConsulta
     */
    public PanelSequenciaConsulta(long id, ControladorPresentacioSequencies controladorSequencies) {
        this.controladorSequencies = controladorSequencies;

        initComponents();

        omplirCamps(id);
        
        jTextAreaSequencia.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSequencia = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setText("Seqüència:");

        jTextAreaSequencia.setBackground(new java.awt.Color(239, 242, 249));
        jTextAreaSequencia.setColumns(20);
        jTextAreaSequencia.setEditable(false);
        jTextAreaSequencia.setLineWrap(true);
        jTextAreaSequencia.setRows(5);
        jTextAreaSequencia.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaSequencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaSequencia;
    // End of variables declaration//GEN-END:variables

    private void omplirCamps(Long id) {
        jTextAreaSequencia.setText(controladorSequencies.getSequencia(id));
    }
}
