package edu.upc.prop.presentacio;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PanelSimptomes extends javax.swing.JPanel {

    private ControladorPresentacioSimptomes controladorSimptomes;
    private ControladorPresentacioMalalties controladorMalalties;
    private ControladorPresentacioPacients controladorPacients;
    private PanelSimptomaConsulta panelConsulta;
    private PanelSimptomaDades panelDades;
    private DefaultListModel llistaSimptomes;
    private boolean modificant;
    private int indexActual;

    public PanelSimptomes(ControladorPresentacioSimptomes controladorSimptomes,
            ControladorPresentacioMalalties controladorMalalties, ControladorPresentacioPacients controladorPacients) {
        this.controladorSimptomes = controladorSimptomes;
        this.controladorPacients = controladorPacients;
        this.controladorMalalties = controladorMalalties;
        this.controladorSimptomes.setPanelSimptomes(this);

        llistaSimptomes = new DefaultListModel();

        initComponents();

        jListSimtomes.setModel(llistaSimptomes);

        modificant = false;
        indexActual = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListSimtomes = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        jListSimtomes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSimtomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSimtomesMouseClicked(evt);
            }
        });
        jListSimtomes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListSimtomesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListSimtomes);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListSimtomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSimtomesMouseClicked
        canviaSimptoma();
    }//GEN-LAST:event_jListSimtomesMouseClicked

    private void jListSimtomesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListSimtomesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            canviaSimptoma();
        }
    }//GEN-LAST:event_jListSimtomesKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListSimtomes;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public boolean nouSimptoma() {
        if (modificant) {
            String msg = "Si crees un nou Símptoma sense guardar, es descartaran els canvis actuals. Vols continuar?";
            String title = "No has guardat els canvis!";
            int optionType = JOptionPane.OK_CANCEL_OPTION;
            int msgType = JOptionPane.QUESTION_MESSAGE;
            int opcio = JOptionPane.showConfirmDialog(this, msg, title, optionType, msgType);
            if (opcio == JOptionPane.CANCEL_OPTION) {
                return false;
            }
        }

        jPanel2.removeAll();
        jListSimtomes.clearSelection();
        indexActual = -1;
        panelDades = new PanelSimptomaDades(controladorSimptomes, controladorMalalties,
                controladorPacients);
        jPanel2.add(panelDades);

        touch();
        return true;
    }

    public boolean modificarSimptoma() {
        jPanel2.removeAll();

        int index = jListSimtomes.getSelectedIndex();
        if (index != -1) {
            String simptoma = (String) jListSimtomes.getModel().getElementAt(index);
            panelDades = new PanelSimptomaDades(controladorSimptomes, controladorMalalties,
                    controladorPacients, simptoma);
            jPanel2.add(panelDades);
            indexActual = index;
            touch();
            return true;
        } else {
            String msg = "Ha de seleccionar un simptoma";
            String title = "Modificació simptoma";
            JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public boolean esborrarSimptoma() {
        int index = jListSimtomes.getSelectedIndex();
        String title = "Esborrar simptoma";
        String msg;

        if (index != -1) {
            msg = "Segur que vols esborrar el simptoma seleccionada";
            int option = JOptionPane.showConfirmDialog(this, msg, title, JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                controladorSimptomes.esborrarSimptoma((String) jListSimtomes.getModel().getElementAt(index));

                llistaSimptomes.removeElementAt(index);

                jPanel2.removeAll();
                jListSimtomes.clearSelection();
                indexActual = -1;
                modificant = false;

                touch();
                return true;
            }
        } else {
            msg = "Ha de seleccionar un simptoma";
            JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public boolean seleccioBuida() {
        return jListSimtomes.isSelectionEmpty();
    }

    public void seleccionaSimptoma(String simptoma) {
        jPanel2.removeAll();
        int index = ((DefaultListModel) jListSimtomes.getModel()).indexOf(simptoma);
        jListSimtomes.setSelectedIndex(index);

        panelConsulta = new PanelSimptomaConsulta(simptoma, controladorSimptomes);
        jPanel2.add(panelConsulta);
        indexActual = index;
        modificant = false;
        controladorSimptomes.enableButtonsMainForm();

        touch();
    }

    public void cancelar() {
        jPanel2.removeAll();
        int index = jListSimtomes.getSelectedIndex();
        if (index != -1) {
            String simptoma = (String) ((DefaultListModel) jListSimtomes.getModel()).get(index);
            panelConsulta = new PanelSimptomaConsulta(simptoma, controladorSimptomes);
            jPanel2.add(panelConsulta);
            controladorSimptomes.enableButtonsMainForm();
        }
        touch();
        modificant = false;
        indexActual = index;
    }

    private void touch() {
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    private void canviaSimptoma() {
        int index = jListSimtomes.getSelectedIndex();
        if (index != -1) {
            if (modificant && index != indexActual) {
                String msg = "Si consultes un altre Símptoma sense guardar, es descartaran els canvis actuals. Vols continuar?";
                String title = "No has guardat els canvis!";
                int optionType = JOptionPane.OK_CANCEL_OPTION;
                int msgType = JOptionPane.QUESTION_MESSAGE;
                int opcio = JOptionPane.showConfirmDialog(this, msg, title, optionType, msgType);
                if (opcio == JOptionPane.CANCEL_OPTION) {
                    if (indexActual == -1) {
                        jListSimtomes.clearSelection();
                    } else {
                        jListSimtomes.setSelectedIndex(indexActual);
                    }
                    return;
                }
            }
            if (!(modificant && index == indexActual)) {
                jPanel2.removeAll();
                String simptoma = ((String) jListSimtomes.getModel().getElementAt(index));
                panelConsulta = new PanelSimptomaConsulta(simptoma, controladorSimptomes);
                jPanel2.add(panelConsulta);
                indexActual = index;
                modificant = false;
                controladorSimptomes.enableButtonsMainForm();
            }
            touch();
        }
    }

    public void redibuixar(String simptoma) {
        llistaSimptomes.addElement(simptoma);
    }

    public void setModificant() {
        modificant = true;
    }

    public void refresh() {
        llistaSimptomes.clear();
        for (String simptoma : controladorSimptomes.getNomSimptomes()) {
            llistaSimptomes.addElement(simptoma);
        }
    }
}
